FROM bitnami/spark:3.5.0

USER root

# Instalar dependencias necesarias para acceso a S3A
RUN install_packages curl unzip

# Descargar hadoop-aws y aws-java-sdk-bundle
RUN curl -L -o /opt/bitnami/spark/jars/hadoop-aws-3.3.4.jar https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar \
 && curl -L -o /opt/bitnami/spark/jars/aws-java-sdk-bundle-1.11.1026.jar https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.1026/aws-java-sdk-bundle-1.11.1026.jar

USER 1001
